export default function About() {
  return <article className="reading-page about"><p className="eyebrow">About the archive</p><h1>Return to what matters.</h1><p className="page-description">Sankofa is a thesis archive for students, supervisors, and researchers at the African Institute for Mathematical Sciences.</p>
    <section><h2>Go back and fetch it</h2><p>Sankofa comes from an Akan concept in Ghana: return to the past and retrieve what is valuable. Here, that means keeping earlier scholarship accessible, connecting its ideas, and making it useful to the next researcher.</p></section>
    <section><h2>A scholarly instrument</h2><p>Search by topic, read an abstract, follow connections across campuses and cohorts, export a citation, or ask a question of a thesis. The Oracle proposes directions suggested by the archive’s concept graph. Dreams record exploratory walks through that graph.</p></section>
    <section><h2>Ethics and stewardship</h2><p>A thesis is a person’s work. Author attribution, consent, and usage rights belong with the record. Missing information is shown as missing. A software licence does not determine the licence of a thesis.</p><p>Generated responses and graph suggestions require scholarly verification. A missing connection in this archive is not proof that a topic has never been studied. Questions currently draw on the recorded abstract, rather than the complete thesis text.</p></section>
    <section><h2>Local first</h2><p>Sankofa retains its command line, interactive terminal, and API alongside this web interface. Its backend can run on local infrastructure, using a local language model when available. The web interface needs access to a running archive API.</p></section>
    <section><h2>Keyboard guide</h2><dl className="shortcut-list"><dt>/</dt><dd>Focus the current search field</dd><dt>j / k</dt><dd>Next / previous thesis in the archive</dd><dt>Enter</dt><dd>Open the focused thesis</dd><dt>g h</dt><dd>Go to the archive</dd><dt>g g</dt><dd>Go to the graph</dd><dt>Esc</dt><dd>Clear the current search field</dd><dt>Tab</dt><dd>Move through controls and links</dd></dl></section>
  </article>;
}
